### ISSUE TITLE
Inkscape png to svg covert problem

### ISSUE THREAD

**Issue by gevv** [cdhigh/sprintFontRelease#11]
Hello, files converted from png to svg with Inkscape program cannot be used. "image conversion error" I use the same image by converting it to svg format with online tools, no problem. (Thank you so much for this great plugin)

**Comment by gevv** [comment]
[Desktop.zip](https://github.com/user-attachments/files/18260078/Desktop.zip)

**Comment by cdhigh** [comment]
Because your operation of converting png to svg is incorrect.
The svg file you converted did not contain any paths, instead, it contains a bitmap image only.
I converted your `home.png` by Inkscape and imported it to Sprint-Layout successfully:
![Snipaste](https://github.com/user-attachments/assets/d26a4000-639a-4e47-ac41-095fb1ef5669)

The correct steps are: goto "Path" | "Trace Bitmap", generate paths; and then delete the bitmap image, while keeping the generated paths.
You can search on Google or watch some video tutorials for more details.

**Comment by gevv** [comment]
I did what you said and the problem is solved. Thank you.
