### ISSUE TITLE
Failed to parse file content with any kicad footprint

### ISSUE THREAD

**Issue by zephyrins** [cdhigh/sprintFontRelease#8]
With SprinFront 1.5.3 and also 1.5.2 on windows 11 in VM machine (Parallel with processeur ARM M1) i can't import kicad footprints. I have a popup message Failed to parse file content.

![issue SprintFront KiCad](https://github.com/cdhigh/sprintFontRelease/assets/90088190/8787f154-b3c6-4763-9055-cf628e1fc593)

**Comment by cdhigh** [comment]
Can you upload your footprint file?

**Comment by zephyrins** [comment]
Any Footprint come from  standar kicad library made this issues in my case ...
Easyeda works fine 


I have put the mod file in the zip

[FanPinHeader_1x03_P2.54mm_Vertical.zip](https://github.com/cdhigh/sprintFontRelease/files/14666709/FanPinHeader_1x03_P2.54mm_Vertical.zip)

**Comment by cdhigh** [comment]
When tested on Windows 7 and Windows 10, this file can be imported correctly.   
Since I don't have Windows 11 neither ARM M1 machine, I'm not sure what the problem might be.   
I suspect it's likely related to permissions or file encoding. 
Could you please help test this version and see what errors are outputted?  
https://github.com/cdhigh/sprintFontRelease/releases/download/v1.5.4/sprintFont_v1.5.4.rar

**Comment by zephyrins** [comment]
I just tested it. I get a message from Windows: Microsoft defender SmartScreen which prevents execution because the editor is unknown. If I force the execution the OK button has no effect and I must to cancel.

**Comment by cdhigh** [comment]
It's probably an operating system compatibility issue. If you can install Python, you can directly use Python to execute sprintFont.py to identify the error location. 
If cannot, try this package. This version will keep the terminal window open, and after an error occurs, the terminal window should display more information.
Download again:
https://github.com/cdhigh/sprintFontRelease/releases/download/v1.5.4/sprintFont_v1.5.4.rar

As for concerns about viruses, because the behavior of exe files after python-packaging is somewhat different from regular exe files, it can indeed lead to false positives from antivirus software. However, I always run a check with VirusTotal each time, so there's no need to worry.
https://www.virustotal.com/gui/file/42375a411ab88b0a1b395c893dfd83759fc7b5587fe91c90081969b9c4086e7c?nocache=1

**Comment by zephyrins** [comment]
I have launch your last version  this is the message that i have in the terminal windows

Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Python38\lib\tkinter\__init__.py", line 1892, in __call__
  File "sprintFont.py", line 1327, in cmdOkFootprint_Cmd
  File "sprintFont.py", line 1667, in generateFootprint
AttributeError: 'str' object has no attribute 'isValid'

**Comment by cdhigh** [comment]
ok,
download agagin:
https://github.com/cdhigh/sprintFontRelease/releases/download/v1.5.4/sprintFont_v1.5.4.rar

**Comment by zephyrins** [comment]
No message in the terminal but 2 types of issue depend of location of the file perhaps

![first issue](https://github.com/cdhigh/sprintFontRelease/assets/90088190/d1fd39db-1378-4e03-ac89-af64f2a60126)
![second issue](https://github.com/cdhigh/sprintFontRelease/assets/90088190/d0d0daaf-543d-47ff-af63-6ed630a732cb)

**Comment by cdhigh** [comment]
The second error is as expected, because python of windows version cannot recognize the path like "//mac/...".

The first error is indeed very strange. I just downloaded the latest KiCad footprint again and tested importing the same file on my computer, and everything is normal. Could it really be a compatibility issue with the Windows 11 system or Parallels vm?
download again:
https://github.com/cdhigh/sprintFontRelease/releases/download/v1.5.4/sprintFont_v1.5.4.rar

or can you upload your C_Axial_L3.8mm.... ?

**Comment by zephyrins** [comment]
In reality the System is Windows 11 Pro included with Parallels

Log with  C_Axial_L3.8mm.... on C:

Decoding file using utf-8...
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Python38\lib\tkinter\__init__.py", line 1892, in __call__
  File "sprintFont.py", line 1327, in cmdOkFootprint_Cmd
  File "sprintFont.py", line 1647, in generateFootprint
  File "D:\Electronic\Soft\Sprint-Layout 6.0\sprintFont\kicad_to_sprint.py", line 55, in kicadModToTextIo
  File "D:\Electronic\Soft\Sprint-Layout 6.0\sprintFont\kicad_pcb\kicad_mod.py", line 123, in __init__
IndexError: list index out of range


Log with the last file 

Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Python38\lib\tkinter\__init__.py", line 1892, in __call__
  File "sprintFont.py", line 1327, in cmdOkFootprint_Cmd
  File "sprintFont.py", line 1647, in generateFootprint
  File "D:\Electronic\Soft\Sprint-Layout 6.0\sprintFont\kicad_to_sprint.py", line 55, in kicadModToTextIo
  File "D:\Electronic\Soft\Sprint-Layout 6.0\sprintFont\kicad_pcb\kicad_mod.py", line 69, in __init__
FileNotFoundError: [Errno 2] No such file or directory: '//mac/home/downloads/fanpinheader_1x03_p2.54mm_vertical.kicad_mod'

**Comment by cdhigh** [comment]
Could you upload kicad_mod file?
C_Axial_L3.8mm....

**Comment by zephyrins** [comment]
[C_Axial_L3.8mm_D2.6mm_P7.50mm_Horizontal.zip](https://github.com/cdhigh/sprintFontRelease/files/14718691/C_Axial_L3.8mm_D2.6mm_P7.50mm_Horizontal.zip)

**Comment by cdhigh** [comment]
Your footprint file is of version 8.
sprintFont supports only version 5/6 (There is only version 5/6 when sprintFont was released).

I will revise the code to try to load version 8.

**Comment by cdhigh** [comment]
Let me confirm one thing:
I want to implement compatibility with reading and writing to a shared folder in the Mac virtual machine.

I haven't used Parallels, but I have used VMware on Mac before. When using VMware, setting up a shared folder can be mapped to a drive in Windows, such as `Z:`.

I see you're using this path directly: `//mac/home/downloads/xxx.kicad_mod`.
Can Parallels map a virtual drive?
Can Windows Explorer directly use this path?

**Comment by zephyrins** [comment]
By default the mac is mapping on Z:  with Parallels,  but i can also access directly to the folder of the Mac like Downloads 

See beelow i have used Z: instead of the direct folder

![Mapping Z](https://github.com/cdhigh/sprintFontRelease/assets/90088190/1a00efbc-1a9d-4b5c-89b3-e430d0bf1eb7)

**Comment by cdhigh** [comment]
Ok, thanks, I won't fix this issue because it's already something at the Python implement level and needs Python team to solve. 
Now, you need to copy the `kicad_mod` from the shared directory on the Mac to your Windows system. 

Please download the new package and confirm if it's working properly.
https://github.com/cdhigh/sprintFontRelease/releases/download/v1.5.4/sprintFont_v1.5.4.rar

**Comment by zephyrins** [comment]
Ok it's work fine from a folder on Windows system C:

**Comment by cdhigh** [comment]
Released 1.5.4 final:
https://github.com/cdhigh/sprintFontRelease/releases/download/v1.5.4/sprintFont_v1.5.4.rar
